server:
  port: 9761
#spring:
#  profiles: eureka-server1
eureka:
  instance:
    hostname: eureka-server1
  server:
    enable-self-preservation: false
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
#    registerWithEureka: false
#    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9760/eureka/
spring:
  application:
    name: Application-Eurka-Server1